spring:
  thymeleaf:
    cache: false
  application:
    name: springboot-rest


eureka:
  client:
    service-url:
      defaultZone: http://localhost:30000/eureka/
server:
  port: 30002

security:
  user:
    name: admin
    password: admin
---
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: debug
    org.springframework.web: DEBUG
    org.hibernate: ERROR
---
elasticsearch:
  ip:
  pool: 5
  cluster:
    name: ep-es-cluster
  host: 10.250.112.250
  port: 9200
  schema: http
  connect_time_out: 1000
  socket_time_out: 3000
  connection_request_time_out: 500
  max_connect_num: 100
  max_connect_per_route: 100
  uniqueConnectTimeConfig : false
  uniqueConnectNumConfig: true


