spring:
  security:
    user:
      name: admin
      password: admin
  thymeleaf:
    cache: false
  application:
    name: springboot-rest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:30000/eureka/
server:
  port: 30002

