spring:
  thymeleaf:
    cache: false
  application:
    name: springboot-rest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:30000/eureka/
server:
  port: 30002

security:
  user:
    name: admin
    password: admin
---
mybatis:
  configuration:
    map-underscore-to-camel-case: true


